### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/outreach.uiowa.edu#24]
Pending further guidance from OSC regarding the use of open sourced fonts, start with:
Gotham for headers
Archer for body

https://assets.uiowa.edu/fonts/index.html

**Comment by GaryRidgway** [comment]
should be complete in https://github.com/ITS-UofIowa/outreach.uiowa.edu/commit/3fc0d1aacc45473aedd5b7d221be01a06aea2875

**Comment by joewhitsitt** [comment]
These fonts aren't being imported to the theme.

e.g. `@import url('https://assets.uiowa.edu/css/gotham.css');`

**Comment by joewhitsitt** [comment]
https://github.com/ITS-UofIowa/outreach.uiowa.edu/commit/c3dde483c7cb05e8b43e900c62092f57adf97710
